FROM python:3.12-slim

RUN pip install --no-cache-dir datasette==1.0a24 datasette-write-ui==0.0.1a14

RUN adduser --disabled-password --no-create-home datasette-user

USER datasette-user

EXPOSE 8001

CMD ["datasette", "/app/data/", \
     "--host", "0.0.0.0", \
     "--port", "8001", \
     "--setting", "allow_execute_sql", "on"]
